"""upgrade to factories 2

Revision ID: 10f31c5e5a17
Revises: 1da90aa3a9c
Create Date: 2014-03-05 15:52:46.031000

"""

# revision identifiers, used by Alembic.
revision = '10f31c5e5a17'
down_revision = '1da90aa3a9c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factoryWastage',
    sa.Column('factoryWastageId', sa.Integer(), nullable=False),
    sa.Column('modelId', sa.Integer(), nullable=True),
    sa.Column('FactoryID', sa.Integer(), nullable=True),
    sa.Column('VaccineName', sa.String(length=250), nullable=True),
    sa.Column('WastageFraction', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['modelId'], ['models.modelId'], ),
    sa.PrimaryKeyConstraint('factoryWastageId')
    )
    op.create_table('initialOVW',
    sa.Column('initialOVWId', sa.Integer(), nullable=False),
    sa.Column('modelId', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=250), nullable=True),
    sa.Column('OVW', sa.Float(), nullable=True),
    sa.Column('Notes', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['modelId'], ['models.modelId'], ),
    sa.PrimaryKeyConstraint('initialOVWId')
    )
    op.create_table('factories',
    sa.Column('factoryId', sa.Integer(), nullable=False),
    sa.Column('modelId', sa.Integer(), nullable=True),
    sa.Column('idcode', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=250), nullable=True),
    sa.Column('Targets', sa.String(length=250), nullable=True),
    sa.Column('Vaccines', sa.String(length=250), nullable=True),
    sa.Column('ProductionIntervalDays', sa.Float(), nullable=True),
    sa.Column('StartupLatencyDays', sa.Float(), nullable=True),
    sa.Column('OverstockScale', sa.Float(), nullable=True),
    sa.Column('DemandType', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['modelId'], ['models.modelId'], ),
    sa.PrimaryKeyConstraint('factoryId')
    )
    op.drop_table(u'factoryOVW')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'factoryOVW',
    sa.Column(u'factoryOVWId', sa.INTEGER(), nullable=False),
    sa.Column(u'modelId', sa.INTEGER(), nullable=True),
    sa.Column(u'Name', sa.VARCHAR(length=250), nullable=True),
    sa.Column(u'OVW', sa.FLOAT(), nullable=True),
    sa.Column(u'Notes', sa.VARCHAR(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['modelId'], [u'models.modelId'], ),
    sa.PrimaryKeyConstraint(u'factoryOVWId')
    )
    op.drop_table('factories')
    op.drop_table('initialOVW')
    op.drop_table('factoryWastage')
    ### end Alembic commands ###
