"""upgrade_to_include_category_in_vaccine

Revision ID: 125b181e7324
Revises: 149f6a257cb1
Create Date: 2017-04-27 11:17:39.204000

"""

# revision identifiers, used by Alembic.
revision = '125b181e7324'
down_revision = '149f6a257cb1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccinetypes', sa.Column('Category', sa.String(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaccinetypes', 'Category')
    ### end Alembic commands ###
