"""add crashlogs to db

Revision ID: 14620f27dfd8
Revises: 6fc3ce9df65
Create Date: 2017-06-28 13:15:37.119067

"""

# revision identifiers, used by Alembic.
revision = '14620f27dfd8'
down_revision = 'cc5540bfd14'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logBlobHolder',
    sa.Column('blobId', sa.Integer(), nullable=False),
    sa.Column('tickId', sa.Integer(), nullable=True),
    sa.Column('blob', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['tickId'], ['tickProcess.tickId'], ),
    sa.PrimaryKeyConstraint('blobId')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logBlobHolder')
    ### end Alembic commands ###
