"""upgrade to factories

Revision ID: 1da90aa3a9c
Revises: 285b4768292c
Create Date: 2014-03-04 11:33:02.528000

"""

# revision identifiers, used by Alembic.
revision = '1da90aa3a9c'
down_revision = '285b4768292c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
