"""update to 1569

Revision ID: 1f72fe425541
Revises: 52b8a4216b32
Create Date: 2013-12-13 17:33:13.192000

"""

# revision identifiers, used by Alembic.
revision = '1f72fe425541'
down_revision = '52b8a4216b32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storeCapHistBlobHolder',
    sa.Column('blobId', sa.Integer(), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('blobId')
    )
    op.create_table('vaHistBlobHolder',
    sa.Column('blobId', sa.Integer(), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('blobId')
    )
    op.create_table('transCapHistBlobHolder',
    sa.Column('blobId', sa.Integer(), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('blobId')
    )
    op.add_column(u'results', sa.Column('storeCapJsonRef', sa.Integer(), nullable=True))
    op.add_column(u'results', sa.Column('tranportCapJsonRef', sa.Integer(), nullable=True))
    op.add_column(u'results', sa.Column('vaccineAvailJsonRef', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'results', 'vaccineAvailJsonRef')
    op.drop_column(u'results', 'tranportCapJsonRef')
    op.drop_column(u'results', 'storeCapJsonRef')
    op.drop_table('transCapHistBlobHolder')
    op.drop_table('vaHistBlobHolder')
    op.drop_table('storeCapHistBlobHolder')
    ### end Alembic commands ###
