"""upgrade to 1515

Revision ID: 216efc659e0d
Revises: 2512bc078649
Create Date: 2013-11-08 11:23:25.913127

"""

# revision identifiers, used by Alembic.
revision = '216efc659e0d'
down_revision = '2512bc078649'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccinetypes', sa.Column('Manufacturer', sa.String(length=250), nullable=True))
    op.add_column('vaccinetypes', sa.Column('secondaryPackaging', sa.String(length=250), nullable=True))
    op.add_column('vaccinetypes', sa.Column('coolerMonths', sa.Float(), nullable=True))
    op.add_column('vaccinetypes', sa.Column('freezerMonths', sa.Float(), nullable=True))
    op.add_column('vaccinetypes', sa.Column('link', sa.String(length=250), nullable=True))
    op.add_column('vaccinetypes', sa.Column('openMonths', sa.Float(), nullable=True))
    op.add_column('vaccinetypes', sa.Column('roomtempMonths', sa.Float(), nullable=True))
    # wastageRate removal moved to next alembic version
    #op.drop_column('vaccinetypes', u'wastageRate')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # wastageRate addition moved to next alembic version
    #op.add_column('vaccinetypes', sa.Column(u'wastageRate', sa.FLOAT(), nullable=True))
    op.drop_column('vaccinetypes', 'roomtempMonths')
    op.drop_column('vaccinetypes', 'openMonths')
    op.drop_column('vaccinetypes', 'link')
    op.drop_column('vaccinetypes', 'freezerMonths')
    op.drop_column('vaccinetypes', 'coolerMonths')
    op.drop_column('vaccinetypes', 'secondaryPackaging')
    op.drop_column('vaccinetypes', 'Manufacturer')
    ### end Alembic commands ###
