"""adding modelGeoJson

Revision ID: 23ef41cec1b7
Revises: 3c82bc4a5c7a
Create Date: 2016-06-17 16:35:33.177000

"""

# revision identifiers, used by Alembic.
revision = '23ef41cec1b7'
down_revision = '3c82bc4a5c7a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelGeoJsonBlobHolder',
    sa.Column('blobId', sa.Integer(), nullable=False),
    sa.Column('blob', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('blobId')
    )
    try:
        op.alter_column('modelGeoJsonBlobHolder', 'blob',
                   existing_type=sa.BLOB(),
                   type_=mysql.LONGBLOB(),
                   existing_nullable=True) 
    except:
        pass
    op.add_column('models', sa.Column('modelGeoJsonRef', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'modelGeoJsonRef')
    op.drop_table('modelGeoJsonBlobHolder')
    ### end Alembic commands ###
