"""add cost keypoints jsons

Revision ID: 2b46615e1cd9
Revises: 50d27dc19d68
Create Date: 2015-07-11 13:39:46.162000

"""

# revision identifiers, used by Alembic.
revision = '2b46615e1cd9'
down_revision = '50d27dc19d68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costSummaryKeyPointsBlobHolder',
    sa.Column('blobId', sa.Integer(), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('blobId')
    )
    op.add_column(u'results', sa.Column('costSummaryKeyPointsJsonRef', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'results', 'costSummaryKeyPointsJsonRef')
    op.drop_table('costSummaryKeyPointsBlobHolder')
    ### end Alembic commands ###
