"""add runtable

Revision ID: 2e15e69fbdab
Revises: 339bd4130db6
Create Date: 2016-03-10 09:30:47.007000

"""

# revision identifiers, used by Alembic.
revision = '2e15e69fbdab'
down_revision = '339bd4130db6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('runId', sa.Integer(), nullable=False),
    sa.Column('startTime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('endTime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('modelId', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=250), nullable=True),
    sa.Column('run_location', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['modelId'], ['models.modelId'], ),
    sa.PrimaryKeyConstraint('runId')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    ### end Alembic commands ###
