"""add hierarchical costs jsons

Revision ID: 339bd4130db6
Revises: 2b46615e1cd9
Create Date: 2015-07-11 14:15:00.692000

"""

# revision identifiers, used by Alembic.
revision = '339bd4130db6'
down_revision = '2b46615e1cd9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hierarchicalCostSummaryTreeMapBlobHolder',
    sa.Column('blobId', sa.Integer(), nullable=False),
    sa.Column('blob',sa.dialects.mysql.LONGBLOB(),nullable=True),
    #sa.Column('blob', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('blobId')
    )
    op.create_table('hierarchicalCostSummaryBarChartBlobHolder',
    sa.Column('blobId', sa.Integer(), nullable=False),
    sa.Column('blob',sa.dialects.mysql.LONGBLOB(),nullable=True),
   # sa.Column('blob', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('blobId')
    )
    op.add_column(u'results', sa.Column('hierarchicalCostSummaryBarChartJsonRef', sa.Integer(), nullable=True))
    op.add_column(u'results', sa.Column('hierarchicalCostSummaryTreeMapJsonRef', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'results', 'hierarchicalCostSummaryTreeMapJsonRef')
    op.drop_column(u'results', 'hierarchicalCostSummaryBarChartJsonRef')
    op.drop_table('hierarchicalCostSummaryBarChartBlobHolder')
    op.drop_table('hierarchicalCostSummaryTreeMapBlobHolder')
    ### end Alembic commands ###
