"""added model d3 json

Revision ID: 38d52ac1af36
Revises: 40a5c363f7d4
Create Date: 2015-04-02 11:46:52.897000

"""

# revision identifiers, used by Alembic.
revision = '38d52ac1af36'
down_revision = '40a5c363f7d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('factoryOVW')
    op.create_index('factoryIdx', 'factories', ['modelId', 'idcode'], unique=False)
    op.add_column('models', sa.Column('modelD3JsonRef', sa.Integer(), nullable=True))
    op.create_index('routesIdxName', 'routes', ['modelId', 'RouteName'], unique=False)
    op.create_index('stopsIdxId', 'stops', ['modelId', 'idcode'], unique=False)
    op.create_index('stopsIdxRn', 'stops', ['modelId', 'RouteName'], unique=False)
    op.create_index('storesIdx', 'stores', ['modelId', 'idcode'], unique=False)
    op.create_index('typesIdx', 'types', ['modelId', 'Name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('typesIdx', table_name='types')
    op.drop_index('storesIdx', table_name='stores')
    op.drop_index('stopsIdxRn', table_name='stops')
    op.drop_index('stopsIdxId', table_name='stops')
    op.drop_index('routesIdxName', table_name='routes')
    op.drop_column('models', 'modelD3JsonRef')
    op.drop_index('factoryIdx', table_name='factories')
    #op.create_table('factoryOVW',
    #sa.Column('factoryOVWId', sa.INTEGER(), nullable=False),
    #sa.Column('modelId', sa.INTEGER(), nullable=True),
    #sa.Column('Name', sa.VARCHAR(length=250), nullable=True),
    #sa.Column('OVW', sa.FLOAT(), nullable=True),
    #sa.Column('Notes', sa.VARCHAR(length=4096), nullable=True),
    #sa.ForeignKeyConstraint(['modelId'], [u'models.modelId'], ),
    #sa.PrimaryKeyConstraint('factoryOVWId')
    #)
    ### end Alembic commands ###
