"""add_model_summary_blob_holder

Revision ID: 3ac2bb5bd921
Revises: 1f3ad17351bb
Create Date: 2014-12-05 14:55:06.671000

"""

# revision identifiers, used by Alembic.
revision = '3ac2bb5bd921'
down_revision = '1f3ad17351bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelSummaryBlobHolder',
    sa.Column('blobId', sa.Integer(), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('blobId')
    )
    op.add_column(u'models', sa.Column('modelSummaryJsonRef', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'models', 'modelSummaryJsonRef')
    op.drop_table('modelSummaryBlobHolder')
    ### end Alembic commands ###
