"""'add_power_outage_to_stores'

Revision ID: 3c82bc4a5c7a
Revises: 20433a9a815a
Create Date: 2016-04-23 17:08:50.306000

"""

# revision identifiers, used by Alembic.
revision = '3c82bc4a5c7a'
down_revision = '20433a9a815a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('PowerOutageDurationDays', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('PowerOutageDurationSigma', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('PowerOutageFrequencyPerYear', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'PowerOutageFrequencyPerYear')
    op.drop_column('stores', 'PowerOutageDurationSigma')
    op.drop_column('stores', 'PowerOutageDurationDays')
    ### end Alembic commands ###
