"""add micro1 cost tables

Revision ID: 3d9c8b4b7acd
Revises: 1b8bcdb45b07
Create Date: 2014-09-21 21:20:07.068642

"""

# revision identifiers, used by Alembic.
revision = '3d9c8b4b7acd'
down_revision = '1b8bcdb45b07'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    
    #
    #  Add code to:
    #  -move OUTDOORS to 2012
    #
    
    op.create_table('microCostSummary',
    sa.Column('micro1CostSummaryId', sa.Integer(), nullable=False),
    sa.Column('ReportingLevel', sa.String(length=250), nullable=True),
    sa.Column('ReportingBranch', sa.String(length=250), nullable=True),
    sa.Column('ReportingIntervalDays', sa.Float(), nullable=True),
    sa.Column('DaysPerYear', sa.Float(), nullable=True),
    sa.Column('Currency', sa.String(length=250), nullable=True),
    sa.Column('BaseYear', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['micro1CostSummaryId'], ['costSummary.summaryId'], ),
    sa.PrimaryKeyConstraint('micro1CostSummaryId')
    )
    op.create_table('microCostSummaryEntry',
    sa.Column('micro1SummaryEntryId', sa.Integer(), nullable=False),
    sa.Column('costSummaryGrpId', sa.Integer(), nullable=True),
    sa.Column('costCategory', sa.String(length=250), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['costSummaryGrpId'], ['microCostSummary.micro1CostSummaryId'], ),
    sa.PrimaryKeyConstraint('micro1SummaryEntryId')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('microCostSummaryEntry')
    op.drop_table('microCostSummary')
    ### end Alembic commands ###
