"""test11111

Revision ID: 45acb861cdb5
Revises: 38d52ac1af36
Create Date: 2015-04-02 12:13:31.881000

"""

# revision identifiers, used by Alembic.
revision = '45acb861cdb5'
down_revision = '38d52ac1af36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
