"""'upgrade_trucks_and_stores_to_have_cats'

Revision ID: 4e0eaf0351e6
Revises: 125b181e7324
Create Date: 2017-05-03 15:01:05.518000

"""

# revision identifiers, used by Alembic.
revision = '4e0eaf0351e6'
down_revision = '125b181e7324'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storagetypes', sa.Column('DisplayCategory', sa.String(length=250), nullable=True))
    op.add_column('trucktypes', sa.Column('Category', sa.String(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trucktypes', 'Category')
    op.drop_column('storagetypes', 'DisplayCategory')
    ### end Alembic commands ###
