"""upgrade to 1415

Revision ID: 4f6f88162aac
Revises: ac511c4a13f
Create Date: 2013-08-30 02:28:16.336000

"""

# revision identifiers, used by Alembic.
revision = '4f6f88162aac'
down_revision = 'ac511c4a13f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storeVialsBlobHolder',
    sa.Column('blobId', sa.Integer(), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('blobId')
    )
    op.add_column(u'storesRpt', sa.Column('storeVialCount_multival', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'storesRpt', 'storeVialCount_multival')
    op.drop_table('storeVialsBlobHolder')
    ### end Alembic commands ###
