"""add cost summary jsons

Revision ID: 50d27dc19d68
Revises: 716b20e2745
Create Date: 2015-07-11 11:46:44.114000

"""

# revision identifiers, used by Alembic.
revision = '50d27dc19d68'
down_revision = '716b20e2745'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costSummaryResultsBlobHolder',
    sa.Column('blobId', sa.Integer(), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('blobId')
    )
    op.add_column(u'results', sa.Column('costSummaryResultsJsonRef', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'results', 'costSummaryResultsJsonRef')
    op.drop_table('costSummaryResultsBlobHolder')
    ### end Alembic commands ###
