"""add legacy cost summary

Revision ID: 5535d37cb69f
Revises: 230f55ad2536
Create Date: 2014-08-27 14:32:11.761454

"""

# revision identifiers, used by Alembic.
revision = '5535d37cb69f'
down_revision = '230f55ad2536'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costSummary',
    sa.Column('summaryId', sa.Integer(), nullable=False),
    sa.Column('costClass', sa.String(length=30), nullable=True),
    sa.Column('resultsId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resultsId'], ['results.resultsId'], ),
    sa.PrimaryKeyConstraint('summaryId')
    )
    op.create_table('legacyCostSummary',
    sa.Column('legacySummaryId', sa.Integer(), nullable=False),
    sa.Column('ReportingLevel', sa.String(length=250), nullable=True),
    sa.Column('ReportingBranch', sa.String(length=250), nullable=True),
    sa.Column('ReportingIntervalDays', sa.Float(), nullable=True),
    sa.Column('DaysPerYear', sa.Float(), nullable=True),
    sa.Column('Currency', sa.String(length=250), nullable=True),
    sa.Column('RouteTrips', sa.Integer(), nullable=True),
    sa.Column('PerDiemDays', sa.Integer(), nullable=True),
    sa.Column('CostingTreatmentDays', sa.Integer(), nullable=True),
    sa.Column('PerDiemCost', sa.Float(), nullable=True),
    sa.Column('PerKmCost', sa.Float(), nullable=True),
    sa.Column('PerTripCost', sa.Float(), nullable=True),
    sa.Column('TransportCost', sa.Float(), nullable=True),
    sa.Column('LaborCost', sa.Float(), nullable=True),
    sa.Column('StorageCost', sa.Float(), nullable=True),
    sa.Column('BuildingCost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['legacySummaryId'], ['costSummary.summaryId'], ),
    sa.PrimaryKeyConstraint('legacySummaryId')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legacyCostSummary')
    op.drop_table('costSummary')
    ### end Alembic commands ###
