"""Added GeoResultsJson Blob

Revision ID: 716b20e2745
Revises: 45acb861cdb5
Create Date: 2015-05-10 01:08:57.789000

"""

# revision identifiers, used by Alembic.
revision = '716b20e2745'
down_revision = '45acb861cdb5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('geoResultsJsonRef', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'geoResultsJsonRef')
    ### end Alembic commands ###
