"""Upgrade to r1349 where we start using Alembic

Revision ID: 955a591d00d
Revises: None
Create Date: 2013-07-17 18:33:48.017095

"""

# revision identifiers, used by Alembic.
revision = '955a591d00d'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultsGroup',
    sa.Column('resultsGroupId', sa.Integer(), nullable=False),
    sa.Column('modelId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['modelId'], ['models.modelId'], ),
    sa.PrimaryKeyConstraint('resultsGroupId')
    )
    op.create_table('results',
    sa.Column('resultsId', sa.Integer(), nullable=False),
    sa.Column('resultsGroupId', sa.Integer(), nullable=True),
    sa.Column('runNumber', sa.Integer(), nullable=True),
    sa.Column('resultsType', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['resultsGroupId'], ['resultsGroup.resultsGroupId'], ),
    sa.PrimaryKeyConstraint('resultsId')
    )
    op.create_table('storesRpt',
    sa.Column('storesRptId', sa.Integer(), nullable=False),
    sa.Column('resultsId', sa.Integer(), nullable=True),
    sa.Column('modelId', sa.Integer(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('category', sa.String(length=250), nullable=True),
    sa.Column('function', sa.String(length=250), nullable=True),
    sa.Column('one_vaccine_outages', sa.Float(), nullable=True),
    sa.Column('overstock_time', sa.Float(), nullable=True),
    sa.Column('stockout_time', sa.Float(), nullable=True),
    sa.Column('tot_delivery_vol', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['modelId'], ['models.modelId'], ),
    sa.ForeignKeyConstraint(['resultsId'], ['results.resultsId'], ),
    sa.PrimaryKeyConstraint('storesRptId')
    )
    op.create_table('routesRpt',
    sa.Column('routesRptId', sa.Integer(), nullable=False),
    sa.Column('resultsId', sa.Integer(), nullable=True),
    sa.Column('modelId', sa.Integer(), nullable=True),
    sa.Column('RouteName', sa.String(length=250), nullable=True),
    sa.Column('RouteFill', sa.Float(), nullable=True),
    sa.Column('RouteTrips', sa.Float(), nullable=True),
    sa.Column('RouteTruckType', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['modelId'], ['models.modelId'], ),
    sa.ForeignKeyConstraint(['resultsId'], ['results.resultsId'], ),
    sa.PrimaryKeyConstraint('routesRptId')
    )
    op.create_table('vaxrpt',
    sa.Column('vaxRptId', sa.Integer(), nullable=False),
    sa.Column('storesRptId', sa.Integer(), nullable=True),
    sa.Column('vax', sa.String(length=250), nullable=True),
    sa.Column('expired', sa.Float(), nullable=True),
    sa.Column('outages', sa.Float(), nullable=True),
    sa.Column('patients', sa.Float(), nullable=True),
    sa.Column('treated', sa.Float(), nullable=True),
    sa.Column('vials', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['storesRptId'], ['storesRpt.storesRptId'], ),
    sa.PrimaryKeyConstraint('vaxRptId')
    )
    op.create_table('storageRpt',
    sa.Column('storageRptId', sa.Integer(), nullable=False),
    sa.Column('storesRptId', sa.Integer(), nullable=True),
    sa.Column('storageType', sa.String(length=250), nullable=True),
    sa.Column('fillRatio', sa.Float(), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('vol_used', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['storesRptId'], ['storesRpt.storesRptId'], ),
    sa.PrimaryKeyConstraint('storageRptId')
    )
    op.alter_column(u'stops', u'isSupplier',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'stops', u'isSupplier',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_table('storageRpt')
    op.drop_table('vaxrpt')
    op.drop_table('routesRpt')
    op.drop_table('storesRpt')
    op.drop_table('results')
    op.drop_table('resultsGroup')
    ### end Alembic commands ###
