"""Add privilege tables

Revision ID: ac511c4a13f
Revises: f93eccf2fc5
Create Date: 2013-08-16 19:00:47.484535

"""

# revision identifiers, used by Alembic.
revision = 'ac511c4a13f'
down_revision = 'f93eccf2fc5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prvgroups',
    sa.Column('groupId', sa.Integer(), nullable=False),
    sa.Column('groupName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('groupId')
    )
    op.execute("INSERT INTO prvgroups VALUES (1,'sysgroup')")
    op.execute("INSERT INTO prvgroups VALUES (2,'everyone')")
    
    op.create_table('prvusers',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.execute('INSERT INTO prvusers VALUES (1,"system")')
    op.execute('INSERT INTO prvusers VALUES (2,"anyone");')
    
    op.create_table('prvusergroupassociation',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['prvgroups.groupId'], ),
    sa.ForeignKeyConstraint(['user_id'], ['prvusers.userId'], ),
    sa.PrimaryKeyConstraint()
    )
    op.execute("INSERT INTO prvusergroupassociation VALUES (1,1)")
    op.execute("INSERT INTO prvusergroupassociation VALUES (1,2)")
    op.execute("INSERT INTO prvusergroupassociation VALUES (2,2)")

    op.create_table('prvmodelaccessrights',
    sa.Column('primKey', sa.Integer(), nullable=False),
    sa.Column('modelId', sa.Integer(), nullable=True),
    sa.Column('ownerId', sa.Integer(), nullable=True),
    sa.Column('readGroupId', sa.Integer(), nullable=True),
    sa.Column('writeGroupId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modelId'], ['models.modelId'], ),
    sa.ForeignKeyConstraint(['ownerId'], ['prvusers.userId'], ),
    sa.ForeignKeyConstraint(['readGroupId'], ['prvgroups.groupId'], ),
    sa.ForeignKeyConstraint(['writeGroupId'], ['prvgroups.groupId'], ),
    sa.PrimaryKeyConstraint('primKey')
    )
    op.execute("""
    INSERT INTO prvmodelaccessrights (modelId, ownerId, readGroupId, writeGroupId)
    SELECT modelId, '2', '2', '2' FROM models;
    """)
    
    #op.drop_table(u'sessionModel')
    try:
        op.alter_column(u'stops', u'isSupplier',
                   existing_type=mysql.TINYINT(display_width=1),
                   type_=sa.Boolean(),
                   existing_nullable=True)
    except:
        pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    try:
        op.alter_column(u'stops', u'isSupplier',
                        existing_type=sa.Boolean(),
                        type_=mysql.TINYINT(display_width=1),
                        existing_nullable=True)
    except:
        pass
    op.create_table(u'sessionModel',
    sa.Column(u'sessionModelId', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'modelId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column(u'sessionId', mysql.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['modelId'], [u'models.modelId'], name=u'sessionModel_ibfk_1'),
    sa.ForeignKeyConstraint(['sessionId'], [u'uisessions.sessionId'], name=u'sessionModel_ibfk_2'),
    sa.PrimaryKeyConstraint(u'sessionModelId'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('prvmodelaccessrights')
    op.drop_table('prvusergroupassociation')
    op.drop_table('prvusers')
    op.drop_table('prvgroups')
    ### end Alembic commands ###
