"""update to 1435

Revision ID: fd6bb381a6e
Revises: 4f6f88162aac
Create Date: 2013-09-26 18:04:16.071000

"""

# revision identifiers, used by Alembic.
revision = 'fd6bb381a6e'
down_revision = '4f6f88162aac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('kmlVizStringRef', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'kmlVizStringRef')
    ### end Alembic commands ###
