<p>Help Text:</p>
<br>
<p>The available models table lists your existing models. Clicking any row in your list of models will select that model, allowing you to perform the following tasks:</p>
<br>
<ul>
<li>You can create a full copy of a model by selecting the <b>Copy</b> button.  This is helpful if you would like to alter or edit the model to create a new system.
<li>To permanently remove a model, select <b>Delete</b> and confirm. This will also remove any results that have been generated by running this model. 
<li>To view or make changes to a model, select <b>Open</b>. This directs users to the model page, which shows the transportation network diagram and allows users to modify, copy, run, view results, or export the selected model.
</ul>