<p>{{_('The available models table lists your existing models. Double-click any row in the list to open a dialog, allowing you to edit the name of the model and add/edit a note for that model. Notes are optional and will not affect how the model runs')}}:</p>
<br>
<ul>
<li>{{_('You can create a full copy of a model by selecting the Copy button.  This is helpful if you would like to alter or edit the model to create a new system.')}}
<li>{{_('To permanently remove a model, select Del and confirm. This will also remove any results that have been generated by running this model.')}} 
<li>{{_('To view or make changes to a model, select Open. This directs to the model page, which shows the supply chain network diagram and allows users to modify, run, view results, or export the selected model.')}}
</ul>