print _('Next Step')
print _('Vials Used')
print _('Doses Demanded')
print _('Doses Administered')
print _('Percent Stored 2 to 8 C')
print _('Percent Stored Below 2C')
print _('Vaccine Results')
print _('Overall Totals')
print _('Availability by Location')
print _('Number of Locations')
print _('Maximum Storage')
print _('Utilization by Location')
print _('Maximum Transport')
print _('Utilization by Location')
print _('Number Of Routes')
print _('Open Geographic Visualization')
print _('Open Network Visualization')
print _('Download Excel Results Spreadsheet')
print _('Total Costs By Supply Chain Level')
print _('Products Begin Here')
print _('Products Terminate Here')
print _('Location')
print _('Locations')
print _('fixed frequency')
print _('frequency as needed')
print _('shipments per')
print _('transit time')
print _('distance')
print _('fixed amount')
print _('demand based amount')
print _('Pick Up or Receive Shipments?')
print _('Scheduled or Demand-Based Schedule of Shipments')
print _('Amount of Shipment Fixed or Demand Based')
print _('Frequency of Shipments')
print _('per')
print _('Number of Locations Supplied by this Location')
print _('Next Screen')
print _('Previous Screen')
print _('Skip to Model Editor')
print _('Available Types')
print _('Used Types')
print _('Location Name')
print _('Include in the dose table?')
print _('How many doses of each vaccine per person per year?')
print _('Showing demand for')
print _('Submit')
print _('Show Advanced Options')
print _('Validating Model')
print _('Major Errors Exist')
print _('Major Costing Errors Exist')
print _('Your model has costing errors in it that could lead to erroneous results.  You will not be able to run the simulation until this is corrected.') 
print _('You must correct these by editing the models costing page. Click the button at the bottom of the dialog labelled Go To Cost Model Editor to do this.')
print _("Go To Advanced Model Editor")
print _("Go To Cost Model Editor")
print _("Run Simulation")
print _("Must give the run a name before proceeding")

